<?php
/**
 * @author  Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2022 Tigren Solutions <https://www.tigren.com>. All rights reserved.
 * @license  Open Software License (“OSL”) v. 3.0
 */

/** @var $block \Tigren\CustomerGroupCatalogRule\Block\Catalog\Product\View\AddTo\Compare */
?>

<?php if (in_array($block->getProduct()->getSku(), $block->getProductInRule())) : ?>
    <?php if ($block->isHideAddToCompare()) : ?>
        <span></span>
    <?php else: ?>
        <?php $viewModel = $block->getData('addToCompareViewModel'); ?>
        <?php if ($viewModel->isAvailableForCompare($block->getProduct())) : ?>
            <a href="#" data-post='<?= /* @noEscape */
            $block->getPostDataParams() ?>'
               data-role="add-to-links"
               class="action tocompare"><span><?= $block->escapeHtml(__('Add to Compare')) ?></span></a>
        <?php endif; ?>
    <?php endif; ?>
<?php else: ?>
    <?php $viewModel = $block->getData('addToCompareViewModel'); ?>
    <?php if ($viewModel->isAvailableForCompare($block->getProduct())) : ?>
        <a href="#" data-post='<?= /* @noEscape */
        $block->getPostDataParams() ?>'
           data-role="add-to-links"
           class="action tocompare"><span><?= $block->escapeHtml(__('Add to Compare')) ?></span></a>
    <?php endif; ?>
<?php endif; ?>


